name: ydata_profiling_env
channels:
  - conda-forge
  - defaults
dependencies:
  - pip=24.3.1
  - pandas=2.3.2
  - ydata-profiling=4.18.1
  - jupyter_core=5.8.1
  - pyarrow=21.0.0
  - ipywidgets=8.1.7
  - pip:
      - wandb==0.24.0
