name: ex4_eda
channels:
  - conda-forge
  - defaults
dependencies:
  - jupyterlab=4.4.7
  - seaborn=0.13.2
  - pandas=2.3.2
  - pip=24.3.1
  - ydata-profiling=4.18.1
  - pyarrow=21.0.0
  - ipywidgets=8.1.7
  - pip:
      - wandb==0.24.0
      - setuptools==75.3.4

